package org.wso2.carbon.application.upload;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T15:33:22.185+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://upload.application.carbon.wso2.org", name = "CarbonAppUploaderPortType")
@XmlSeeAlso({org.wso2.carbon.application.upload.xsd.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CarbonAppUploaderPortType {

    @Action(input = "urn:uploadApp", output = "urn:uploadAppResponse")
    @WebMethod(action = "urn:uploadApp")
    public void uploadApp(
        @WebParam(partName = "parameters", name = "uploadApp", targetNamespace = "http://upload.application.carbon.wso2.org")
        UploadApp parameters
    );
}
