package org.wso2.carbon.application.upload;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T15:33:22.254+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "CarbonAppUploader", 
                  wsdlLocation = "CarbonAppUploader.wsdl",
                  targetNamespace = "http://upload.application.carbon.wso2.org") 
public class CarbonAppUploader extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://upload.application.carbon.wso2.org", "CarbonAppUploader");
    public final static QName CarbonAppUploaderHttpsSoap12Endpoint = new QName("http://upload.application.carbon.wso2.org", "CarbonAppUploaderHttpsSoap12Endpoint");
    public final static QName CarbonAppUploaderHttpsSoap11Endpoint = new QName("http://upload.application.carbon.wso2.org", "CarbonAppUploaderHttpsSoap11Endpoint");
    public final static QName CarbonAppUploaderHttpsEndpoint = new QName("http://upload.application.carbon.wso2.org", "CarbonAppUploaderHttpsEndpoint");
    static {
        URL url = CarbonAppUploader.class.getResource("CarbonAppUploader.wsdl");
        if (url == null) {
            url = CarbonAppUploader.class.getClassLoader().getResource("CarbonAppUploader.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CarbonAppUploader.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CarbonAppUploader.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CarbonAppUploader(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CarbonAppUploader(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarbonAppUploader() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CarbonAppUploader(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CarbonAppUploader(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CarbonAppUploader(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CarbonAppUploaderPortType
     */
    @WebEndpoint(name = "CarbonAppUploaderHttpsSoap12Endpoint")
    public CarbonAppUploaderPortType getCarbonAppUploaderHttpsSoap12Endpoint() {
        return super.getPort(CarbonAppUploaderHttpsSoap12Endpoint, CarbonAppUploaderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarbonAppUploaderPortType
     */
    @WebEndpoint(name = "CarbonAppUploaderHttpsSoap12Endpoint")
    public CarbonAppUploaderPortType getCarbonAppUploaderHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(CarbonAppUploaderHttpsSoap12Endpoint, CarbonAppUploaderPortType.class, features);
    }
    /**
     *
     * @return
     *     returns CarbonAppUploaderPortType
     */
    @WebEndpoint(name = "CarbonAppUploaderHttpsSoap11Endpoint")
    public CarbonAppUploaderPortType getCarbonAppUploaderHttpsSoap11Endpoint() {
        return super.getPort(CarbonAppUploaderHttpsSoap11Endpoint, CarbonAppUploaderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarbonAppUploaderPortType
     */
    @WebEndpoint(name = "CarbonAppUploaderHttpsSoap11Endpoint")
    public CarbonAppUploaderPortType getCarbonAppUploaderHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(CarbonAppUploaderHttpsSoap11Endpoint, CarbonAppUploaderPortType.class, features);
    }
    /**
     *
     * @return
     *     returns CarbonAppUploaderPortType
     */
    @WebEndpoint(name = "CarbonAppUploaderHttpsEndpoint")
    public CarbonAppUploaderPortType getCarbonAppUploaderHttpsEndpoint() {
        return super.getPort(CarbonAppUploaderHttpsEndpoint, CarbonAppUploaderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarbonAppUploaderPortType
     */
    @WebEndpoint(name = "CarbonAppUploaderHttpsEndpoint")
    public CarbonAppUploaderPortType getCarbonAppUploaderHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(CarbonAppUploaderHttpsEndpoint, CarbonAppUploaderPortType.class, features);
    }

}
